image: gitpod/workspace-dotnet
vscode:
  extensions:
    - muhammad-sammy.csharp@1.23.9:BMArOoGwWqKRrH6s4E2/AQ==
    - ionide.ionide-fsharp@5.3.2:ktwOdXq2H8VHS6SX8scVIw==
tasks:
- command: sudo docker-up
ports:
  - port: 7000
    visibility: public
    onOpen: ignore
  - port: 8000
    visibility: public
    onOpen: ignore
  - port: 8080
    visibility: public
    onOpen: ignore