image: gitpod/workspace-dotnet
vscode:
  extensions:
    - muhammad-sammy.csharp
    - ionide.ionide-fsharp
    - syler.sass-indented
tasks:
  - command: dotnet restore ./src/client/FableApp/FableApp.fsproj
ports:
  - port: 7000
    visibility: public
    onOpen: ignore
  - port: 8000
    visibility: public
    onOpen: ignore
  - port: 8080
    visibility: public
    onOpen: ignore
