version: '3.3'

services:
  fable-client:
    image: mcr.microsoft.com/dotnet/sdk:5.0-focal
    container_name: fable-client
    volumes:
      - /workspace/refactor-2021:/workspace/refactor-2021
    working_dir: /workspace/refactor-2021
    command: >
      bash -c "dotnet tool restore && dotnet fable watch ./src/client/FableApp/FableApp.fsproj --outDir ./src/client/src/bin"
  snowpack:
    image: node:14.16
    container_name: snowpack
    volumes:
      - /workspace/refactor-2021/src/client:/app
    ports:
      - "8080:8080"
    environment:
      SNOWPACK_PUBLIC_NODE_API: $SNOWPACK_PUBLIC_NODE_API
      SNOWPACK_PUBLIC_DOTNET_API: $SNOWPACK_PUBLIC_DOTNET_API
    depends_on:
      - fable-client
    working_dir: /app
    command: >
      bash -c "npm i && npm start"
  node-function:
    container_name: node-function
    build:
      context: ./
      dockerfile: NodeJs.Dockerfile
    ports:
      - "7000:7000"
  dotnet-function:
    container_name: dotnet-function
    image: mcr.microsoft.com/azure-functions/dotnet:3.0.3284-dotnet3-core-tools
    volumes:
      - /workspace/refactor-2021/src/server:/app
    ports:
      - "8000:8000"
    working_dir: /app/dotnet
    command: func start --csharp --port 8000 --verbose --cors *